<?php

namespace App\Providers;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * The array to hold repositories.
     *
     * @var array
     */
    protected $repositories = [
        \App\Repositories\Config\Ads\AdsRepository::class                       => \App\Repositories\Config\Ads\AdsRepositoryImplement::class,
        \App\Repositories\Config\Client\ClientRepository::class                 => \App\Repositories\Config\Client\ClientRepositoryImplement::class,
        \App\Repositories\Config\HotelRoom\HotelRoomRepository::class           => \App\Repositories\Config\HotelRoom\HotelRoomRepositoryImplement::class,
        \App\Repositories\Config\UserData\UserDataRepository::class             => \App\Repositories\Config\UserData\UserDataRepositoryImplement::class,
        \App\Repositories\Config\SocialPlugin\SocialPluginRepository::class     => \App\Repositories\Config\SocialPlugin\SocialPluginRepositoryImplement::class,
        \App\Repositories\Config\VoucherPrint\VoucherPrintRepository::class     => \App\Repositories\Config\VoucherPrint\VoucherPrintRepositoryImplement::class
    ];

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        foreach ($this->repositories as $interface => $implement) {
            $this->app->bind($interface, $implement);
        }
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {

        /* This code is checking if the application is running in the production environment and if it
            is, it forces all URLs generated by the application to use the HTTPS scheme. */
        if ($this->app->environment('production')) {
            URL::forceScheme('https');
        }

        /* Sets the default string length for database migrations to 200 characters. */
        Schema::defaultStringLength(200);
    }
}
