<?php

namespace App\Providers;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

// Repositories
use App\Repositories\Config\Ads\AdsRepository;
use App\Repositories\Config\Ads\AdsRepositoryImplement;
use App\Repositories\Config\Client\ClientRepository;
use App\Repositories\Config\Client\ClientRepositoryImplement;
use App\Repositories\Config\HotelRoom\HotelRoomRepository;
use App\Repositories\Config\HotelRoom\HotelRoomRepositoryImplement;
use App\Repositories\Config\UserData\UserDataRepository;
use App\Repositories\Config\UserData\UserDataRepositoryImplement;
use App\Repositories\Config\SocialPlugin\SocialPluginRepository;
use App\Repositories\Config\SocialPlugin\SocialPluginRepositoryImplement;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        // Instantiable Repositories in Sub-Folders
        $this->app->bind(
            ClientRepository::class,
            ClientRepositoryImplement::class
        );
        $this->app->bind(
            HotelRoomRepository::class,
            HotelRoomRepositoryImplement::class
        );
        $this->app->bind(
            AdsRepository::class,
            AdsRepositoryImplement::class
        );
        $this->app->bind(
            UserDataRepository::class,
            UserDataRepositoryImplement::class
        );
        $this->app->bind(
            SocialPluginRepository::class,
            SocialPluginRepositoryImplement::class
        );
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {

        /* This code is checking if the application is running in the production environment and if it
            is, it forces all URLs generated by the application to use the HTTPS scheme. */
        if ($this->app->environment('production')) {
            URL::forceScheme('https');
        }

        /* Sets the default string length for database migrations to 200 characters. */
        Schema::defaultStringLength(200);
    }
}
